apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "nginx-date.fullname" . }}-ingress
  labels:
    helm.sh/chart: {{ include "nginx-date.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
#    - host: {{ include "nginx-date.fullname" . }}-service
#      http:
     - http:        
        paths:
          - path: /
            backend:
              serviceName: {{ include "nginx-date.fullname" . }}
              servicePort: 8081
