apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-date.fullname" . }}
  labels:
{{ include "nginx-date.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "nginx-date.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
